version: "3.8"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  cid-checker-frontend:
    image: cid-checker-frontend
    restart: always

  cid-checker-api:
    image: cid-checker-api
    restart: always
    environment:
      - CID_DB_CONNECTIONSTRING=mongodb://mongo:27017
      - CID_DB_NAME='cid_checker_watcher'
      - CID_LOTUS_RPCURL=http://localhost:1234/rpc/v0
      - CID_LOTUS_JWT_TOKEN=''
      - PORT=3000
    depends_on:
      - mongo

  cid-checker-watcher:
    image: cid-checker-watcher
    restart: always
    environment:
      - CID_DB_CONNECTIONSTRING=mongodb://mongo:27017
      - CID_DB_NAME='cid_checker_watcher'
      # TODO: localhost can't be used here
      - CID_LOTUS_RPCURL=http://localhost:1234/rpc/v0
      - CID_LOTUS_JWT_TOKEN=''
      - SLEEP_TIPSET_CHECK_MS=25000
    depends_on:
      - mongo

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data:
